// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: 'AIzaSyD4usgWjlEMpzdckL6WO8shs9Gpvo1pkJ4',
//       appId: '1:523296260220:android:3696e2bef3753e3cbc09f9',
//       messagingSenderId: '523296260220',
//       projectId: 'safri-c7aa3',
//       storageBucket: 'safri-c7aa3.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: 'AIzaSyA_T09HJnokXNv0F_8oB0nvIAo2WFHMeCs',
//       appId: '1:523296260220:ios:e39b82c36c4e3328bc09f9',
//       messagingSenderId: '523296260220',
//       projectId: 'safri-c7aa3',
//       storageBucket: 'safri-c7aa3.appspot.com',
//       iosBundleId: 'com.safariRestaurant.pavilion',
//   );
//
// }
